name: Backport bot

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport closed pull request
    steps:
      - uses: sbrunner/backport-action@v1.0.0
        with:
          token: ${{ secrets.BACKPORT_GITHUB_TOKEN }}
